### ISSUE TITLE
Design doc review #1 MVP and Schema

### ISSUE THREAD

**Issue by aracpyon** [wpstonebraker/PhanCamp#1]
**MVP**

- [x] It's a minor thing, but change the date to starting date (looks like your data is your finishing date right now) 
- [x] (User auth) Decide how you are going to implement your signup page. Bandcamp has different signup page for the artist sign up. The fan signup is modal and artist sign up is on a separate [page](https://bandcamp.com/signup). What you should do here, instead of building two different signup pages, PRETEND EVERYONE IS ARTIST. So instead of modal for the fan signup, follow the artist signup page, which is [this](https://bandcamp.com/signup).  
  When you have an extra time, then build a fan page but this will be a bonus MVP and please use this [resource](https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/modalbnb) when the time comes . 
- [x] (User Auth) Make sure to print error messages when user signsup/logs in with wrong information. The error messages should be printed like BandCamp does.
- [x] (Artist Page) On the artist page, there is a tab called `music` and when you click it, it will show you all the albums that belongs to the artist as thumbnails. When you click that thumbnail, it will lead you to the detail information about the album with the player. Make sure of this flow when you create the user interface with your react.  
- [x] (Upload/Download) There wouldn't have time to work on the new MVP on the last Friday. Change the dates to fit into the schedule. 

**Schema**
- [x] (Users) Since you are treating all users are artist, either you delete the column of `is_artist` or set it default to be true. 
- [x] (Collections) What is the purpose of this table?
- [x] You will need to make a `genre` table and `genre-tag` joins table between `users` and `genre` tables because user can have many genre-tags.

**Comment by wpstonebraker** [comment]
Thanks for the feedback Ara! I will work on it if I finish the morning
project early today.

The collections table is for purchased tracks, seen here on the user
profile dashboard... but now that I think about it, it doesn't really need
a joins table? Maybe I could store an array of purchased track_ids on the
user?

I will refactor to include the tags. I wasn't sure if we should include
them since the MVP list didn't specify them, but it makes sense to combine
them with genre.

Thank you again!

**Comment by aracpyon** [comment]
- [x] I see. I didn't know the collections was for the purchase. That makes sense. Let's keep the collections table and add `(bonus)` to the table name because this will be a bonus feature. 
I also forgot to mention this. 
- [x] (uploading/downloading) For this feature you need AWS, and please use this [resource](https://open.appacademy.io/learn/swe-in-person-nyc/full-stack-project/active-storage-and-aws-s3-hosting-demo) when you set up AWS.

**Comment by aracpyon** [comment]
**Polymorphism resources**
- [Rails doc on polyorphism](https://guides.rubyonrails.org/association_basics.html#polymorphic-associations)
- examples (in migration)
```ruby
class CreateLikes < ActiveRecord::Migration[5.1]
  def change
    create_table :likes do |t|
      t.integer :user_id
      t.references :likeable, polymorphic: true, index: true
      
      t.timestamps
    end
    add_index :likes, [:user_id, :likeable_type, :likeable_id], unique: true
  end
end
```

if you don't use `t.references`, you have to write below
```Ruby
  def change
    t.bigint :likeable_id
    t.string :likeable_type => comments, artworks
  end
  add_index :likes, [:likeable_type, :imageable_id]
  add_index :user_view [:user_id, :article_id]
```

**Comment by aracpyon** [comment]
Please check the previous post above^  sorry I accidentally closed the issue.

**how do we know when to use polymorphism**

- polymorphism allows a model belongs to more than one other model, with a single association.

- Polymorphism gives you options. For example, there are `Toy`, `Cat`, and `Dog`. Toy can belong to either `Cat` or `Dog`. In this case, polymorphism would work. Also, between `Comment` & `Like`& `Post`, `Like` belongs to either `comment` or `post`. Good case to use polymorphism.

- a/A project resources for polymorphism: Check `likes` table from Art Share on w6d4, `comments` table from Goal app on w7d3, `user_votes` table from Reddit clone on w8d1 

- However, between `Post`, `Sub` and `User` in many to many relationships(like `RedditClone project` on w8d1), in this case, `Post` has to belong both `Sub` and `User` to exist. Belonging to only one of them wouldn't help. In this case, you need a joins table between `Post` and `Sub` called PostSubs and you wouldn't use polymorphism association in this case. (Check `cheers` table from Goal App w7d3)

**how to apply polymorphism to `genres` table for BandCamp**
Make `Polymorphic joins table`!

`Genres table` has only `id`, `name`:
| id | name | created_at | updated_at |
| 1  | rock. |
| 2  | rap |
| 3  | kpop |
| 4  | jazz |

Polymorphic genre's join table is just like `Likes` table that can be belongs to both `Comments` and `Posts` (`Likes` is not a joins table. It's polymorphic). It has a `user_id` and `likeable-id` and `likeable-type`. In your case, genre-joins table should not only be a polymorphic table but also joins table. If you don't use `polymorphic-joins table`, you probably should make three different `joins tables` between `genre` and each of `artist`, `track`, `album` such as...

`user-genres table`
id | genre_id | user_id |. created_at | updated_at
1  |  1             | 2
2 |   2            | 2
3 |  3             | 2
4 |  2             | 3

`album-genres table`
| id | genre_id | album_id |. created_at | updated_at
| 1  |       1        |  5
| 2  |      2        |  4
| 3  |      3        |  5
| 4  |      2        |  4

`track-genres table`
| id | genre_id | album_id | created_at | updated_at
| 1  |        1       |  2
| 2  |       2       |  1
| 3  |       3       |  1
| 4  |       2       |  1

However, it is redundant to make three different tables for each type of entities with `Genres`. Therefore, you are adopting `polymorphic relationship` here:

`genre-joins` (you can name it differently)
id | genre_id | genreable-id |  genreable-type | created_at | updated_at
1  |     1          |        1               |       User              |
2  |     2         |        1               |       Album           |
3  |     3         |        5              |       Track             |
4  |     2         |        1               |       User              |

Hope this make sense!

**Comment by wpstonebraker** [comment]
Thanks so much Ara for the resources. Sorry it has taken me so long to figure it all out. I think have a better grasp of it now after looking at the projects and the databases. So as far as I can see, the genre-joins table, the generable-id and generable-type are inherited from its "parent"?

 user paul is an artist that plays classical and jazz
he has a rock album too

User { id: 14, username: paul }
album { id: 22, title: "pauls rock album" }
genres { id: 4, name: "classical" }, {id: 5, name: "jazz" }, {id: 6, name: "rock }

genre_joins would be where these are all connected?
{ id: 1, genre_id: 4, genreable_id: 14, generable_type: user}
{ id: 2, genre_id: 5, genreable_id: 14, generable_type: user} 
 - this shows that user[14] / paul is associated with classical and jazz
 
And users, albums, tracks would not have a genre column anymore, correct? The genre joins would be doing all the work of connecting everything?

I'm still confused, but feel a lot better than I did a couple days ago. Thank you!
{ id: 3, genre_id: 6, genreable_id: 22, generable_type: album }
- this shows that album 22 / "pauls rock album" is associated with the genre rock

i hope the above example makes sense to you. Im going to work on it now

**Comment by aracpyon** [comment]
Correct. I think you are getting it correctly. So the genre-joins table is doing all the jobs that users-genre, albums-genre, tracks-genre were doing. So under the `genre-joins` table:
{ id: 1, genre_id: 4, genreable_id: 14, generable_type: user}
{ id: 2, genre_id: 5, genreable_id: 14, generable_type: user} 
{ id: 3, genre_id: 6, genreable_id: 22, generable_type: album }

You will see all these information together

**Comment by aracpyon** [comment]
And please change the dates on MVP! For example....
1. Hosting on Heroku (01.19.2021) => today
2. New account creation, login, guest/demo login (01.21.2021, 2 days) => The official starting day of this MVP is 01.20.2021 (or `01.19.2021`, since you started it today)
